title: My Jekyll Site
description: a Charity activity sign up website
url: https://ry-000.github.io/Connect/

markdown: kramdown
theme: jekyll-theme-primer

plugins:
  - jekyll-feed
  - jekyll-seo-tag
